apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.frontend.configMap.name }}
data:
  config.js: |
    window._env_ = {
      API_URL: "http://{{ .Values.backend.name }}.{{ .Values.namespace }}.svc.cluster.local:{{ .Values.backend.service.port }}/api"
    };

